Allow customising hotkeys, fixes #53
ferdium/ferdium-app pull request #1920
Opened 2024-10-10 13:23 UTC by insidewhy

#### Pre-flight Checklist

Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/HEAD/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.

#### Description of Change
Allow customising certain shortcuts, for now just "activate next service" and "activate previous service".

#### Motivation and Context

Ctrl+tab and ctrl+shift+tab are not so ergonomic and this is an action that I use very frequently. This has been requested.

#### Screenshots

#### Checklist

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`pnpm prepare-code`)
- [x] `pnpm test` passes
- [x] I tested/previewed my changes locally

#### Release Notes

Allow customising the keyboard shortcuts used to activate the next and previous services.

2024-10-11 08:30 UTC, vraravam commented
@insidewhy  - thanks for submitting the PR. Could you please also attach screenshots of the preference pane,  and maybe a small video on how this feature works?

2024-10-11 10:22 UTC, insidewhy commented
@vraravam I can capture a video of interacting with the preference dialogues but the changes to the keybindings can't be captured with a screen video unless I also video me using my computer keyboard

2024-10-11 11:21 UTC, vraravam commented
> @vraravam I can capture a video of interacting with the preference dialogues but the changes to the keybindings can't be captured with a screen video unless I also video me using my computer keyboard

np - I was able to test this functionality out in my laptop. For future reference, you can use an app like [keycastr](https://github.com/keycastr/keycastr) to capture key bindings and mouse clicks to demonstrate them

1 suggestion: for macos, the `Cmd+tab` is used to switch between running applications, and so I would suggest that you change the keybinding to be `Ctrl+tab` and `Ctrl+Shift+tab` for macos as well.

2024-10-11 16:52 UTC, insidewhy commented
@vraravam thanks for the suggestions. The default key bindings were taken from the current key bindings used by the app, so I didn't want to change them as part of this PR or it would impact the existing functionality of the app.

2024-10-11 16:56 UTC, insidewhy commented
@vraravam thanks for the suggestions. The default key bindings were taken from the current key bindings used by the app, so I didn't want to change them as part of this PR or it would impact the existing functionality of the app.

I suppose this collision between Mac system keybindings and the app has been an issue all this while. If you want to fix it along with this PR I'm happy to do so.

2024-10-11 17:01 UTC, vraravam commented
@insidewhy  - i noticed (after I posted the above comment), that I used to use `Option+Cmd+<left/right arrow>` for moving in forward/reverse direction of services. So, yes, i agree that this was a "clash" already pre-existing in ferdium.

That being said, yes, if you can please update the PR to fix this clash, let's have that bug fixed! Thanks!

2024-10-12 00:24 UTC, vraravam requested changes
change requested as per prev comment. Also, please resolve conflicts by rebasing (not merging) from the `develop` branch

2024-10-12 05:11 UTC, insidewhy commented
> @insidewhy - i noticed (after I posted the above comment), that I used to use `Option+Cmd+<left/right arrow>` for moving in forward/reverse direction of services. So, yes, i agree that this was a "clash" already pre-existing in ferdium.
> 
> That being said, yes, if you can please update the PR to fix this clash, let's have that bug fixed! Thanks!

Just to make sure, you want the default binding for mac to be `⌘+tab` or `ctrl+tab`? Currently it's `Cmd+Tab`.

2024-10-12 05:18 UTC, insidewhy commented
@vraravam BTW I also noticed that changing the shortcuts does not require a restart, so I can remove that message.

2024-10-12 05:30 UTC, insidewhy commented
> change requested as per prev comment. Also, please resolve conflicts by rebasing (not merging) from the `develop` branch

Done

2024-10-12 09:48 UTC, vraravam approved these changes
LGTM! Thanks for the contribution @insidewhy

2024-10-12 09:48 UTC, merged

2024-10-12 09:49 UTC, vraravam commented
@all-contributors please add @insidewhy for code

2024-10-12 10:02 UTC, insidewhy commented
@vraravam Thanks for your help and for merging this so quickly 🎄