Feature: Google Keep as Todos
ferdium/ferdium-app pull request #247
Opened 2022-06-13 16:00 UTC by SpecialAro

#### Pre-flight Checklist

1. Please remember that if you are logging a bug for some service that has _stopped working_ or is _working incorrectly_, please log the bug [here](https://github.com/ferdium/ferdium-recipes/issues)
2. If you are requesting support for a **new service** in Ferdium, please log it [here](https://github.com/ferdium/ferdium-recipes/pulls)
3. Please remember to read the [self-help documentation](https://github.com/ferdium/ferdium-app#troubleshooting-recipes-self-help) - in case it helps you unblock yourself for issues related to older versions of recipes that were installed on your machine. (These will get automatically upgraded when you upgrade to the newer versions of Ferdium, but to get new recipes between Ferdium releases, this documentation is quite useful.)
4. Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

#### Description of Change
Feature: Google Keep as Todos

#### Motivation and Context
Feature: Google Keep as Todos. Fix #197, even though we have an option of setting a custom TODO URL as server.

#### Screenshots
| ![image](https://user-images.githubusercontent.com/37463445/173395330-b3f0f661-4a2d-4e55-b268-924d24cb397f.png) | ![image](https://user-images.githubusercontent.com/37463445/173395366-0b1391b5-c7fb-4d22-9db4-5bff05a58915.png) |
|-- |-- |

#### Checklist

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`npm run prepare-code`)
- [x] `npm test` passes
- [x] I tested/previewed my changes locally

#### Release Notes

2022-06-13 17:00 UTC, vraravam requested changes

2022-06-13 17:00 UTC, vraravam commented on src/config.ts
> +  [TODO_GOOGLETASKS_URL]: 'Google Tasks',
these need to refer to the names of recipes - there's no recipe called "Google Tasks"

2022-06-13 17:00 UTC, vraravam commented on src/config.ts
> +  [TODO_GOOGLEKEEP_URL]: 'google-keep',
the recipe name is "googlekeep"

2022-06-13 23:26 UTC, vraravam approved these changes

2022-06-13 23:28 UTC, merged

2022-06-14 09:14 UTC, yarons commented
I'm wondering if there's a way to make it look good in a narrow sidebar, there are lots of missing details in narrow screen.

2022-06-14 09:30 UTC, SpecialAro commented
> I'm wondering if there's a way to make it look good in a narrow sidebar, there are lots of missing details in narrow screen.

Most likely by injecting some CSS code you can achieve it.