Fix vertical sidebar rendering overlapping the active service
ferdium/ferdium-app pull request #70
Opened 2022-04-30 15:20 UTC by SpecialAro

#### Pre-flight Checklist

1. Please remember that if you are logging a bug for some service that has _stopped working_ or is _working incorrectly_, please log the bug [here](https://github.com/ferdium/ferdium-recipes/issues)
2. If you are requesting support for a **new service** in Ferdium, please log it [here](https://github.com/ferdium/ferdium-recipes/pulls)
3. Please remember to read the [self-help documentation](https://github.com/ferdium/ferdium-app#troubleshooting-recipes-self-help) - in case it helps you unblock yourself for issues related to older versions of recipes that were installed on your machine. (These will get automatically upgraded when you upgrade to the newer versions of Ferdium, but to get new recipes between Ferdium releases, this documentation is quite useful.)
4. Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

#### Description of Change
Fix vertical sidebar rendering overlapping the active service.

#### Motivation and Context
Fixes the vertical sidebar rendering on top of app. This solves the issue https://github.com/ferdium/ferdium-app/issues/69 and was due (blames) to the PR https://github.com/ferdium/ferdium-app/pull/58 merged to the codebase.

Confirmed to work with:
- [ ] Mac
- [ ] Linux
- [x] Windows

#### Checklist

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`npm run prepare-code`)
- [x] `npm test` passes
- [x] I tested/previewed my changes locally

#### Release Notes
Fix vertical sidebar rendering overlapping the active service

2022-04-30 15:44 UTC, vraravam requested changes
Please also delete trailing spaces in the files.

2022-04-30 15:44 UTC, vraravam commented on src/features/appearance/index.ts
> +const isWindows = process.platform === 'win32';
There's a constant already exported for `isWindows` from `environment.ts` - please use that

2022-04-30 15:47 UTC, vraravam commented on src/features/appearance/index.ts
> +const isWindows = process.platform === 'win32';
Fixed in latest commit

2022-04-30 15:59 UTC, vraravam commented
looks good on macos! 
<img width="84" alt="Screenshot_2022-04-30_at_10 58 32_AM" src="https://user-images.githubusercontent.com/69629/166113067-302ed1e2-84a0-4282-b2e7-fec93343a1bb.png">

2022-04-30 16:02 UTC, vraravam approved these changes

2022-05-01 10:59 UTC, SpecialAro commented
Tested on Linux as well, all working fine
![image](https://user-images.githubusercontent.com/37463445/166142991-18c4c47a-2d1e-468d-8a1e-df31a545255f.png)

2022-05-01 11:34 UTC, merged